#!/usr/bin/env python3
"""gen_zh_charsets.py — OpenCC 사전에서 간체/번체 판정 집합을 뽑아 Go 소스로 굽는다.

왜 생성하나. 2026-09-17 에 간체·번체 오염을 손으로 고른 82자 정규식으로 쓸었고
«168 → 0» 이라 보고했다. 완전한 OpenCC 표로 다시 재니 **430건이 남아 있었다** —
鄭·賢·東·煥·張·碩·貞·錫·趙 … 목록에 없던 글자였다. 사람이 고른 목록은 반드시
샌다. 사전에서 굽는다.

판정 규칙(각 글자 C):
  번체전용 = TSCharacters 의 키이고, 자기 자신을 대응값에 포함하지 않으며,
             STCharacters 의 키도 아니다.
  간체전용 = STCharacters 의 키이고, 자기 자신을 대응값에 포함하지 않으며,
             TSCharacters 의 키도 아니다. 단 **대만 표준형은 뺀다**.

  자기 자신을 대응값에 포함하면 그 글자는 양쪽에서 정자다 — 里·于·斗·准·台·采·
  朴·姜 가 여기 걸린다. 첫 대응값만 보면(v[0]!=k) 이들을 오염으로 잡아 한국
  성씨 «박»을 樸 으로 바꾸는 사고가 난다. 실제로 그렇게 133건을 오염시켰다.

  대만 표준형(TWVariants 의 대응값): 秘·床·羣→群 처럼 «간체처럼 보이지만 대만에서
  쓰는 정자». 이것을 빼지 않으면 驚喜神秘沙龍 을 오염으로 잡는다.

변환 표는 **왕복 안정한 1:1 쌍만** 싣는다. s2t(t2s(C)) == C 인 것만.
  鄭→郑→鄭 ✓ 싣는다        昇→升→升 ✗ 뺀다(이체자 — 昇 은 인명에서 살아 있다)
불안정한 글자는 감지는 되지만 자동 변환하지 않는다. 사람이 본다.
"""
import os
import sys

HEADER = "// Code generated by scripts/gen_zh_charsets.py; DO NOT EDIT.\n"


def load(d, name):
    m = {}
    with open(os.path.join(d, name), encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line:
                continue
            parts = line.split("\t")
            if len(parts) < 2 or len(parts[0]) != 1:
                continue
            m[parts[0]] = [v for v in parts[1].split(" ") if v]
    return m


def main():
    if len(sys.argv) < 3:
        sys.exit("usage: gen_zh_charsets.py <opencc-dictionary-dir> <out.go>")
    d, out = sys.argv[1], sys.argv[2]
    ts = load(d, "TSCharacters.txt")   # 번체 → 간체
    st = load(d, "STCharacters.txt")   # 간체 → 번체
    tw = load(d, "TWVariants.txt")     # 번체 → 대만 표준형

    tw_standard = {v for vs in tw.values() for v in vs if len(v) == 1}

    trad_only = sorted(k for k, v in ts.items() if k not in v and k not in st)
    hans_only = sorted(
        k for k, v in st.items() if k not in v and k not in ts and k not in tw_standard
    )

    t2s_from, t2s_to = [], []
    for c in trad_only:
        s = ts[c][0]
        if len(s) == 1 and st.get(s, [s])[0] == c:
            t2s_from.append(c)
            t2s_to.append(s)

    s2t_from, s2t_to = [], []
    for c in hans_only:
        t = st[c][0]
        if len(t) == 1 and ts.get(t, [t])[0] == c:
            s2t_from.append(c)
            s2t_to.append(t)

    def go_const(name, comment, value):
        return '\t// %s\n\t%s = %s\n' % (comment, name, quote(value))

    def quote(s):
        return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

    with open(out, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write("\npackage kdb\n\nconst (\n")
        fh.write(go_const("zhTradOnlyRunes", "번체에서만 정자인 글자 (%d)" % len(trad_only), "".join(trad_only)))
        fh.write("\n")
        fh.write(go_const("zhHansOnlyRunes", "간체에서만 정자인 글자 — 대만 표준형 제외 (%d)" % len(hans_only), "".join(hans_only)))
        fh.write("\n")
        fh.write(go_const("zhT2SFrom", "왕복 안정 번체 (%d)" % len(t2s_from), "".join(t2s_from)))
        fh.write("\n")
        fh.write(go_const("zhT2STo", "위에 대응하는 간체", "".join(t2s_to)))
        fh.write("\n")
        fh.write(go_const("zhS2TFrom", "왕복 안정 간체 (%d)" % len(s2t_from), "".join(s2t_from)))
        fh.write("\n")
        fh.write(go_const("zhS2TTo", "위에 대응하는 번체", "".join(s2t_to)))
        fh.write(")\n")

    print("trad_only=%d hans_only=%d t2s_pairs=%d s2t_pairs=%d tw_standard=%d"
          % (len(trad_only), len(hans_only), len(t2s_from), len(s2t_from), len(tw_standard)))


if __name__ == "__main__":
    main()
